# Generated by Django 5.1.3 on 2026-05-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_esgdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ESGData',
            new_name='RawRecord',
        ),
    ]
