# Generated by Django 5.1.3 on 2026-05-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_esgdata_rawrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fuel', models.FloatField(default=0)),
                ('total_kwh', models.FloatField(default=0)),
                ('flight_km', models.FloatField(default=0)),
                ('co2_emissions', models.FloatField(default=0)),
                ('esg_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
